[project]
name = "ridgefollowing"
version = "0.1.0"
dependencies = [
    "pytest",
    "numpy",
    "numdifftools",
    "numba",
    "pydantic<2.0",
    "energy_surfaces@git+https://github.com/msallermann/energy_surfaces.git@v0.1.0"
]